# Change baseurl before deploy
baseurl = "https://nueck.github.io/"
languageCode = "zh-cn"
paginate = 5
title = "Hello Nueck"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

enableEmoji = true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT = true # 允许爬虫抓取到搜索引擎，建议 true
efaultContentLanguage = "zh-CN"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"